language: python
arch:
  - arm64
  - amd64
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install nosexcover
  - pip install coveralls
  - python setup.py -q install

script:
  nosetests --with-xcoverage --cover-package vcsi.vcsi

after_success:
  coveralls
